DROP INDEX IF EXISTS "medical_records_patient_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "medical_records_record_type_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "medical_records_recorded_date_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "medical_records_recorded_by_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "patients_is_active_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "patients_assigned_volunteer_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "patients_phone_number_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "patients_created_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "patients_verification_status_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "patients_deleted_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "users_role_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "users_is_active_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "users_is_approved_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "users_clerk_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "users_deleted_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "conversation_messages_conversation_state_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "conversation_states_patient_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "conversation_states_deleted_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "manual_confirmations_patient_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "manual_confirmations_volunteer_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "manual_confirmations_reminder_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "manual_confirmations_reminder_type_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "manual_confirmations_confirmation_type_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "manual_confirmations_visit_date_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "manual_confirmations_confirmed_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "manual_confirmations_reminder_confirmation_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminder_logs_reminder_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminder_logs_patient_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminder_logs_action_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminder_logs_timestamp_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_patient_id_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_is_active_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_status_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_type_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_start_date_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_sent_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_confirmation_status_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_deleted_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_priority_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_type_status_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "reminders_active_type_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "whatsapp_templates_category_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "whatsapp_templates_is_active_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "whatsapp_templates_created_by_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "whatsapp_templates_deleted_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_articles_slug_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_articles_status_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_articles_category_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_articles_published_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_articles_created_by_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_articles_deleted_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_videos_slug_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_videos_status_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_videos_category_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_videos_published_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_videos_created_by_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "cms_videos_deleted_at_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "rate_limits_rate_limit_key_idx";--> statement-breakpoint
DROP INDEX IF EXISTS "rate_limits_created_at_idx";